image:
  repository: tccr.io/truecharts/ubooquity
  pullPolicy: IfNotPresent
  tag: v2.1.2

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 2202
        port: 2202

persistence:
  varrun:
    enabled: true
