image:
  repository: tccr.io/truecharts/domoticz
  pullPolicy: IfNotPresent
  tag: v2021.1.20211128

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  varrun:
    enabled: true
