image:
  repository: tccr.io/truecharts/openvscode-server
  pullPolicy: IfNotPresent
  tag: v1.62.3

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000

persistence:
  varrun:
    enabled: true
