image:
  repository: tccr.io/truecharts/openvscode-server
  pullPolicy: IfNotPresent
  tag: openvscode-server

env: {}

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000
