image:
  repository: tccr.io/truecharts/nntp2nntp
  pullPolicy: IfNotPresent
  tag: v0.3.20211116

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 1563
        port: 1563

persistence:
  varrun:
    enabled: true
