image:
  repository: tccr.io/truecharts/boinc
  pullPolicy: IfNotPresent
  tag: v18.04.1

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  varrun:
    enabled: true
