image:
  repository: tccr.io/truecharts/syslog-ng
  pullPolicy: IfNotPresent
  tag: v3.30.1

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 514
        port: 514

persistence:
  varrun:
    enabled: true
