image:
  repository: tccr.io/truecharts/ddclient
  pullPolicy: IfNotPresent
  tag: v3.9.1

env:
  PUID: 568

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  varrun:
    enabled: true
