image:
  repository: tccr.io/truecharts/embystat
  pullPolicy: IfNotPresent
  tag: v0.2.0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 6555
        port: 6555

persistence:
  varrun:
    enabled: true
