image:
  repository: tccr.io/truecharts/minisatip
  pullPolicy: IfNotPresent
  tag: v2021.12.01

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8875
        port: 8875

persistence:
  varrun:
    enabled: true
