image:
  repository: tccr.io/truecharts/code-server
  pullPolicy: IfNotPresent
  tag: v3.12.0@sha256:2853a8bdd8eed9c09bcd4b100b9d4be20c42a307b9d1cbae1a204276e948f9ce

# PASSWORD: password
# SUDO_PASSWORD: password
# HASHED_PASSWORD

env:
  # PROXY_DOMAIN: code-server.my.domain

securityContext:
  AllowPrivilegeEscalation: true

service:
  main:
    ports:
      main:
        port: 10063
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"
