image:
  repository: tccr.io/truecharts/code-server
  pullPolicy: IfNotPresent
  tag: v3.12.0@sha256:2853a8bdd8eed9c09bcd4b100b9d4be20c42a307b9d1cbae1a204276e948f9ce

args:
  - --user-data-dir
  - "/config/.vscode"
  - --auth
  - none

env: {}
  # PROXY_DOMAIN: code-server.my.domain

securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true

service:
  main:
    ports:
      main:
        port: 10063
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: "/config"
