image:
  repository: tccr.io/truecharts/chevereto
  pullPolicy: IfNotPresent
  tag: v1.5.1

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 80

persistence:
  varrun:
    enabled: true
