image:
  repository: tccr.io/truecharts/requestrr
  pullPolicy: IfNotPresent
  tag: v2.1.1

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 4545
        port: 4545

persistence:
  varrun:
    enabled: true
