image:
  repository: tccr.io/truecharts/paperless-ng
  pullPolicy: IfNotPresent
  tag: v1.5.0

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8000
        port: 8000

persistence:
  varrun:
    enabled: true
