image:
  repository: tccr.io/truecharts/darktable
  pullPolicy: IfNotPresent
  tag: v3.4.1

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000

persistence:
  varrun:
    enabled: true
