image:
  repository: tccr.io/truecharts/ngircd
  pullPolicy: IfNotPresent
  tag: v2021.11.21

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 6667
        port: 6667

persistence:
  varrun:
    enabled: true
