image:
  repository: tccr.io/truecharts/synclounge
  pullPolicy: IfNotPresent
  tag: v5.1.111

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8088
        port: 8088

persistence:
  varrun:
    enabled: true
