image:
  repository: tccr.io/truecharts/emulatorjs
  pullPolicy: IfNotPresent
  tag: v1.4.2

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000

persistence:
  varrun:
    enabled: true
