image:
  repository: tccr.io/truecharts/quassel-core
  pullPolicy: IfNotPresent
  tag: v0.13.1

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 4242
        port: 4242

persistence:
  varrun:
    enabled: true
