image:
  repository: tccr.io/truecharts/kodi-headless
  pullPolicy: IfNotPresent
  tag: v190

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080

persistence:
  varrun:
    enabled: true
