image:
  repository: tccr.io/truecharts/mysql-workbench
  pullPolicy: IfNotPresent
  tag: v8.0.27

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 3000

persistence:
  varrun:
    enabled: true
