image:
  repository: tccr.io/truecharts/endlessh
  pullPolicy: IfNotPresent
  tag: v2021.11.21

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 22
        port: 22

persistence:
  varrun:
    enabled: true
