image:
  repository: tccr.io/truecharts/foldingathome
  pullPolicy: IfNotPresent
  tag: v7.6.21

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 7396
        port: 7396

persistence:
  varrun:
    enabled: true
