image:
  repository: tccr.io/truecharts/rsnapshot
  pullPolicy: IfNotPresent
  tag: v1.4.3

env:
  PUID: 568

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

persistence:
  varrun:
    enabled: true
