image:
  repository: tccr.io/truecharts/minetest
  pullPolicy: IfNotPresent
  tag: v5.4.1

env:
  PUID: 568

service:
  main:
    ports:
      main:
        targetPort: 30000
        port: 30000

persistence:
  varrun:
    enabled: true
